/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Toolkit;
import java.sql.ResultSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author angel
 */
public class FrameAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FrameAdmin
     */
    public FrameAdmin() {
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
        this.mostrarTablaEmpleados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_usuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaU = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        rol_combo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_sueldo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        estado_combo = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        panel_habitaciones = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_hab_numero = new javax.swing.JTextField();
        txt_username1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(40, 42, 54));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(40, 42, 54));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(98, 114, 164));
        jTabbedPane1.setForeground(new java.awt.Color(40, 42, 54));
        jTabbedPane1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N

        panel_usuarios.setBackground(new java.awt.Color(98, 114, 164));
        panel_usuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaU.setFont(new java.awt.Font("Roboto Light", 0, 15)); // NOI18N
        tablaU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaUMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaU);

        panel_usuarios.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 950, 200));

        jButton5.setBackground(new java.awt.Color(255, 85, 85));
        jButton5.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panel_usuarios.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 120, 40));

        jButton6.setBackground(new java.awt.Color(255, 121, 198));
        jButton6.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Modificar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panel_usuarios.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 120, 40));

        jPanel5.setBackground(new java.awt.Color(98, 114, 164));
        jPanel5.setForeground(new java.awt.Color(248, 248, 242));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(98, 114, 164));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0};
        jPanel3Layout.rowHeights = new int[] {0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0};
        jPanel3.setLayout(jPanel3Layout);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CURP:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel3.add(jLabel9, gridBagConstraints);

        txt_codigo.setBackground(new java.awt.Color(248, 248, 242));
        txt_codigo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_codigo.setPreferredSize(new java.awt.Dimension(120, 30));
        txt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoActionPerformed(evt);
            }
        });
        txt_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_codigoKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 1, 0);
        jPanel3.add(txt_codigo, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(248, 248, 242));
        jLabel2.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel3.add(jLabel2, gridBagConstraints);

        txt_user.setBackground(new java.awt.Color(248, 248, 242));
        txt_user.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_user.setForeground(new java.awt.Color(68, 71, 90));
        txt_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_userKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 2);
        jPanel3.add(txt_user, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(248, 248, 242));
        jLabel5.setText("Username:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel3.add(jLabel5, gridBagConstraints);

        txt_pass.setBackground(new java.awt.Color(248, 248, 242));
        txt_pass.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(68, 71, 90));
        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_passKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
        jPanel3.add(txt_pass, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(248, 248, 242));
        jLabel3.setText("Nombres:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel3.add(jLabel3, gridBagConstraints);

        txt_nombre.setBackground(new java.awt.Color(248, 248, 242));
        txt_nombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(68, 71, 90));
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
        gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 1);
        jPanel3.add(txt_nombre, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(248, 248, 242));
        jLabel4.setText("Apellidos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel3.add(jLabel4, gridBagConstraints);

        txt_apellido.setBackground(new java.awt.Color(248, 248, 242));
        txt_apellido.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_apellido.setForeground(new java.awt.Color(68, 71, 90));
        txt_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellidoKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 2, 0);
        jPanel3.add(txt_apellido, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(248, 248, 242));
        jLabel8.setText("E-mail:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel3.add(jLabel8, gridBagConstraints);

        txt_email.setBackground(new java.awt.Color(248, 248, 242));
        txt_email.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_email.setForeground(new java.awt.Color(68, 71, 90));
        txt_email.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                txt_emailComponentHidden(evt);
            }
        });
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_emailKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 7, 0);
        jPanel3.add(txt_email, gridBagConstraints);

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, -1));

        jPanel6.setBackground(new java.awt.Color(98, 114, 164));
        jPanel6.setLayout(new java.awt.GridLayout(3, 2, 20, 20));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(248, 248, 242));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Rol:");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel6.add(jLabel14);

        rol_combo.setBackground(new java.awt.Color(248, 248, 242));
        rol_combo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        rol_combo.setForeground(new java.awt.Color(68, 71, 90));
        rol_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recepcionista", "Limpieza" }));
        rol_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rol_comboActionPerformed(evt);
            }
        });
        jPanel6.add(rol_combo);

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(248, 248, 242));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Sueldo:");
        jPanel6.add(jLabel6);

        txt_sueldo.setBackground(new java.awt.Color(248, 248, 242));
        txt_sueldo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_sueldo.setForeground(new java.awt.Color(68, 71, 90));
        txt_sueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_sueldoKeyTyped(evt);
            }
        });
        jPanel6.add(txt_sueldo);

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(248, 248, 242));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Estado:");
        jPanel6.add(jLabel15);

        estado_combo.setBackground(new java.awt.Color(248, 248, 242));
        estado_combo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        estado_combo.setForeground(new java.awt.Color(68, 71, 90));
        estado_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        estado_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estado_comboActionPerformed(evt);
            }
        });
        jPanel6.add(estado_combo);

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 430, 130));

        jButton3.setBackground(new java.awt.Color(80, 250, 123));
        jButton3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(98, 114, 164));
        jButton3.setText("Agregar Empleado");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 200, 40));

        panel_usuarios.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 860, 300));

        jLabel13.setBackground(new java.awt.Color(98, 114, 164));
        jLabel13.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Datos del Empleado");
        panel_usuarios.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jTabbedPane1.addTab("Empleados", panel_usuarios);

        panel_habitaciones.setBackground(new java.awt.Color(98, 114, 164));
        panel_habitaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(98, 114, 164));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 250, 123)), "Datos de la Habitación", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Roboto", 1, 18), new java.awt.Color(248, 248, 242))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(248, 248, 242));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(248, 248, 242));
        jLabel10.setText("Tipo de Habitación");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 56, 160, 33));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(248, 248, 242));
        jLabel11.setText("Num.De Habitación");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, 33));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(248, 248, 242));
        jLabel12.setText("Caracteristicas:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, 33));

        txt_hab_numero.setBackground(new java.awt.Color(248, 248, 242));
        txt_hab_numero.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        txt_hab_numero.setForeground(new java.awt.Color(68, 71, 90));
        txt_hab_numero.setText("jTextField1");
        jPanel4.add(txt_hab_numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 140, -1));

        txt_username1.setBackground(new java.awt.Color(248, 248, 242));
        txt_username1.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        txt_username1.setForeground(new java.awt.Color(68, 71, 90));
        txt_username1.setText("jTextField1");
        jPanel4.add(txt_username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 140, -1));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 444, 240, 10));

        jComboBox1.setBackground(new java.awt.Color(248, 248, 242));
        jComboBox1.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(68, 71, 90));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 140, -1));

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(248, 248, 242));
        jLabel16.setText("Precio: ");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 90, 33));

        jTextArea1.setBackground(new java.awt.Color(248, 248, 242));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(68, 71, 90));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 300, -1));

        panel_habitaciones.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 37, 340, 430));

        jTable2.setBackground(new java.awt.Color(248, 248, 242));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        panel_habitaciones.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 42, 516, -1));

        jButton2.setBackground(new java.awt.Color(80, 250, 123));
        jButton2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(98, 114, 164));
        jButton2.setText("Ingresar Habitación");
        panel_habitaciones.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, 40));

        jTabbedPane1.addTab("Habitaciones", panel_habitaciones);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1000, 670));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1000, 680));

        jLabel1.setBackground(new java.awt.Color(68, 71, 90));
        jLabel1.setFont(new java.awt.Font("Roboto Black", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(248, 248, 242));
        jLabel1.setText("ADMINISTRADOR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jButton7.setBackground(new java.awt.Color(80, 250, 123));
        jButton7.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(98, 114, 164));
        jButton7.setText("Salir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void rol_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rol_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rol_comboActionPerformed

    private void txt_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoActionPerformed

    public void mostrarTablaEmpleados() {
        ConexionMySQL cn = new ConexionMySQL();

        // ResultSet rs = cn.consulta("SELECT codigo,username,password,nombre,apellido,telefono,email,rol  FROM USUARIO");
        cn.ConectarBasedeDatos();
        ResultSet rs = cn.consulta("SELECT codigo, username, nombre, telefono, email, rol FROM usuario where rol!='administrador';");

        try {
            DefaultTableModel dt = new DefaultTableModel();
            dt.addColumn("Codigo");
            dt.addColumn("Username");
            //dt.addColumn("Password");
            dt.addColumn("Nombre");
            // dt.addColumn("Apellido");
            dt.addColumn("Telefono");
            dt.addColumn("Email");
            dt.addColumn("Rol");

            while (rs.next()) {
                Object[] fila = new Object[6];
                fila[0] = rs.getString(1);
                fila[1] = rs.getString(2);
                fila[2] = rs.getString(3);
                fila[3] = rs.getString(4);
                fila[4] = rs.getString(5);
                fila[5] = rs.getString(6);
//                fila[6] = rs.getString(7);
//                fila[7] = rs.getString(8);

                dt.addRow(fila);
            }
            tablaU.setModel(dt);

        } catch (Exception ex) {

        }
    }

    private void tablaUMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUMousePressed

        int filas;

        filas = tablaU.getSelectedRow();

        String codigo = (String) tablaU.getValueAt(filas, 0);
        String user = (String) tablaU.getValueAt(filas, 1);
        //String password = (String) tablaU.getValueAt(filas, 2);
        String nombre = (String) tablaU.getValueAt(filas, 2);
        //String apellido = (String) tablaU.getValueAt(filas, 3);
        String telefono = (String) tablaU.getValueAt(filas, 3);
        String email = (String) tablaU.getValueAt(filas, 4);
        String rol = (String) tablaU.getValueAt(filas, 5);

        txt_codigo.setText(codigo);
        txt_user.setText(user);
        //txt_pass.setText(password);
        txt_nombre.setText(nombre);
        //txt_apellido.setText(apellido);
        txt_sueldo.setText(telefono);
        txt_email.setText(email);
        //   rol_combo.selected(rol);
        //  txt_pass.setText(password);

    }//GEN-LAST:event_tablaUMousePressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        String us = txt_codigo.getText();

        ConexionMySQL cn = new ConexionMySQL();
        cn.ConectarBasedeDatos();

        ResultSet rs = cn.accion("DELETE FROM USUARIO WHERE CODIGO = '" + us + "'");    //' AND USERNAME = '+"+us+"'"); 
        this.mostrarTablaEmpleados();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (isEmail(txt_email.getText())) {
            JOptionPane.showMessageDialog(null, "Correo electrónico inválido", "e-mail inválido", JOptionPane.ERROR_MESSAGE);
        } else {
            String codigo = txt_codigo.getText();
            String user = txt_user.getText();
            String pass = txt_pass.getText();
            String nombre = txt_nombre.getText();
            String apellido = txt_apellido.getText();
            String tele = txt_sueldo.getText();
            String email = txt_email.getText();
            String rol = rol_combo.getSelectedItem().toString();

            ConexionMySQL cn = new ConexionMySQL();
            cn.ConectarBasedeDatos();

            ResultSet rs = cn.accion("UPDATE USUARIO SET USERNAME = '" + user + "',PASSWORD = '" + pass + "',NOMBRE = '" + nombre + "',APELLIDO = '" + apellido + "', TELEFONO = '" + tele + "',EMAIL = '" + email + "',ROL = '" + rol + "'   WHERE CODIGO = '" + codigo + "'");
            this.mostrarTablaEmpleados();
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();
        LogIn a = new LogIn();
        a.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    // Metodo para validar email
    private boolean isEmail(String correo) {
        Pattern pat = Pattern.compile("^([0-9a-zA-Z]([_.w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-w]*[0-9a-zA-Z].)+([a-zA-Z]{2,9}.)+[a-zA-Z]{2,3})$");
        Matcher mat = pat.matcher(correo);

        if (mat.find()) {
            return true;
        } else {
            return false;
        }
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (!isEmail(txt_email.getText())) {
            JOptionPane.showMessageDialog(null, "Correo electrónico inválido", "e-mail inválido", JOptionPane.ERROR_MESSAGE);
        } else {
            String codigo = txt_codigo.getText();
            String user = txt_user.getText();
            String pass = txt_pass.getText();
            String nombre = txt_nombre.getText();
            String apellido = txt_apellido.getText();
            String tele = txt_sueldo.getText();
            String email = txt_email.getText();
            String rol = rol_combo.getSelectedItem().toString();

            ConexionMySQL cn = new ConexionMySQL();
            cn.ConectarBasedeDatos();

            ResultSet rs = cn.agregar("insert into usuario (codigo,username,password,nombre,apellido,telefono,email,rol) values \n"
                    + "('" + codigo + "','" + user + "','" + pass + "','" + nombre + "','" + apellido + "','" + tele + "','" + email + "','" + rol + "');\n"
                            + "create user ");

            /*  ResultSet rs = cn.insertar("insert into usuario (codigo,username,password,nombre,apellido,telefono,email,rol) values \n" +
            "('"+codigo+"',"+user+"',"+pass+"',"+nombre+"',"+apellido+"',"+tele+"',"+email+"'"+rol+"')");*/
            this.mostrarTablaEmpleados();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoKeyTyped
        // TODO add your handling code here:
        if (txt_codigo.getText().length() >= 18) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_codigoKeyTyped

    private void txt_sueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sueldoKeyTyped
        // TODO add your handling code here:
        if (txt_sueldo.getText().length() >= 10) {
            evt.consume();
        } else {
            int key = evt.getKeyChar();
            boolean num = key >= 48 && key <= 57;
            if (!num) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            if (txt_sueldo.getText().trim().length() == 10);
        }
    }//GEN-LAST:event_txt_sueldoKeyTyped

    private void txt_userKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userKeyTyped
        // TODO add your handling code here:
        if (txt_user.getText().length() >= 15) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_userKeyTyped

    private void txt_passKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyTyped
        // TODO add your handling code here:
        if (txt_pass.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_passKeyTyped

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        // TODO add your handling code here:
        if (txt_nombre.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoKeyTyped
        // TODO add your handling code here:
        if (txt_apellido.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_apellidoKeyTyped

    private void txt_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyTyped
        // TODO add your handling code here:
        if (txt_email.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_emailKeyTyped

    private void txt_emailComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_emailComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailComponentHidden

    private void estado_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estado_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estado_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> estado_combo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panel_habitaciones;
    private javax.swing.JPanel panel_usuarios;
    private javax.swing.JComboBox<String> rol_combo;
    private javax.swing.JTable tablaU;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_hab_numero;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_sueldo;
    private javax.swing.JTextField txt_user;
    private javax.swing.JTextField txt_username1;
    // End of variables declaration//GEN-END:variables
}
